# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Andrezio
paginate:       5
baseurl:        "/tale"
url:            "https://chesterhow.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Andre S. B. da Silva
  url:          ""
  email:        andrezio@live.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
